apiVersion: v1
kind: ServiceAccount
metadata:
  name: srtstreamer
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
