name: Build and push all docker images

on:
  pull_request:
    types: [ labeled, opened, synchronize ]
  push:
    branches:
    - main

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64 #, arm64
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Retrieve quay creds from Vault
        id: quay-creds
        uses: hashicorp/vault-action@v3
        with:
          method: jwt
          path: jwt-github-actions
          url: https://telestream-vault-cluster-public-vault-35590643.1620190f.z1.hashicorp.cloud:8200
          namespace: admin 
          role: srtstreamer
          secrets: |
            secret/data/github/srtstreamer/quay username | QUAY_USERNAME;
            secret/data/github/srtstreamer/quay password | QUAY_PASSWORD

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ env.QUAY_USERNAME }}
          password: ${{ steps.quay-creds.outputs.QUAY_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            quay.io/telestream/srtstreamer
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}-{{sha}}

      - name: Build and push alpine-cron
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
